# Generated by Django 4.2.2 on 2023-08-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_cart_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
