# Generated by Django 4.2.2 on 2023-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cart_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cartProductQuantity',
            field=models.PositiveIntegerField(null=True, verbose_name='Quantity'),
        ),
    ]
