# Generated by Django 4.2.2 on 2023-08-25 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0007_alter_cartproducts_cartproductquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.cart', verbose_name='Cart'),
        ),
        migrations.AlterField(
            model_name='cartproducts',
            name='cartByCustomer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
