# Generated by Django 4.2.2 on 2023-09-18 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0009_alter_order_orderedbycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderedByCustomer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='obc', to=settings.AUTH_USER_MODEL, verbose_name='Customer'),
        ),
    ]
