# Generated by Django 4.2.3 on 2023-07-06 08:55

import ckeditor.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerTheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bannerThemeName', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Theme',
            },
        ),
        migrations.CreateModel(
            name='BannerType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bannerTypeName', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Banner Type',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blogTitle', models.CharField(max_length=255, verbose_name='Title')),
                ('blogSubTitle', models.CharField(max_length=255, verbose_name='Sub Title')),
                ('blogImage', models.ImageField(upload_to='fashion/blag/blogimage', verbose_name='Image')),
                ('blogDescription', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('blogStatus', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0, verbose_name='Published or Draft')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('blogAuthor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=255, verbose_name='Name')),
                ('categoryImage', models.ImageField(upload_to='fashion/blog/category', verbose_name='Image')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Blog Category',
                'verbose_name_plural': 'Blog Categories',
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contactUsEmail', models.EmailField(max_length=200, verbose_name='Email')),
                ('contactUsName', models.CharField(max_length=200, verbose_name='Name')),
                ('contactUsNumber', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')], verbose_name='Contact No.')),
                ('contactUsComment', models.TextField(max_length=255, verbose_name='Comment')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Contact Us',
                'verbose_name_plural': 'Contact Us',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('couponCode', models.CharField(max_length=200, unique=True, verbose_name='Code')),
                ('couponType', models.CharField(choices=[('Fixed', 'Fixed'), ('Percentage', 'Percentage')], max_length=255, verbose_name='Type')),
                ('numOfCoupon', models.PositiveIntegerField(default=0, verbose_name='Num. of Coupons')),
                ('couponDiscountOrFixed', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Amount / Discount (%)')),
                ('minAmount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Minimum Amount')),
                ('expirationDateTime', models.DateTimeField(verbose_name='Expiration Date')),
                ('usageLimit', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Usage Limit')),
                ('couponDescription', models.TextField(verbose_name='Description')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.CreateModel(
            name='CouponHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxoapp.coupon', verbose_name='Coupon')),
                ('couponHistoryByOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='Order')),
                ('couponHistoryByUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Coupon History',
                'verbose_name_plural': 'Coupon History',
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255, verbose_name='Comment')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('commentByUser', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('commentOfBlog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voxoapp.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='blogCategory',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='voxoapp.blogcategory', verbose_name='Category'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bannerImage', models.ImageField(upload_to='fashion/banner', verbose_name='Image')),
                ('titleOne', models.CharField(max_length=255, verbose_name='Title One')),
                ('titleTwo', models.CharField(blank=True, max_length=255, verbose_name='Title Two')),
                ('titleThree', models.CharField(blank=True, max_length=255, verbose_name='Title Three')),
                ('titleFour', models.CharField(blank=True, max_length=255, verbose_name='Title Four')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('bannerProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productvariant', verbose_name='Product')),
                ('bannerTheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxoapp.bannertheme', verbose_name='Theme')),
                ('bannerType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voxoapp.bannertype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Banner',
            },
        ),
    ]
