export { default as Loader } from '../..\\components\\loader\\loader.vue'
export { default as PageCart } from '../..\\components\\page\\cart\\cart.vue'
export { default as PageCartTable } from '../..\\components\\page\\cart\\cartTable.vue'
export { default as PageCheckoutMain } from '../..\\components\\page\\checkout\\checkoutMain.vue'
export { default as PageCheckoutPaymentForm } from '../..\\components\\page\\checkout\\paymentForm.vue'
export { default as PageCheckoutTopForm } from '../..\\components\\page\\checkout\\topForm.vue'
export { default as PageCheckoutYourCart } from '../..\\components\\page\\checkout\\yourCart.vue'
export { default as PageContactUsSideSection } from '../..\\components\\page\\contactUs\\contactUsSideSection.vue'
export { default as PageFaqTop } from '../..\\components\\page\\faq\\faqTop.vue'
export { default as PageCompareTable } from '../..\\components\\page\\compare\\compareTable.vue'
export { default as PageOrderDetails } from '../..\\components\\page\\orderSuccess\\orderDetails.vue'
export { default as PageOrderTrackingBottom } from '../..\\components\\page\\orderTracking\\orderTrackingBottom.vue'
export { default as PageOrderTrackingTop } from '../..\\components\\page\\orderTracking\\orderTrackingTop.vue'
export { default as PageSearchProductSlider } from '../..\\components\\page\\search\\productSlider.vue'
export { default as PageSearchTopSearchBar } from '../..\\components\\page\\search\\topSearchBar.vue'
export { default as PageUserDashboardMyDashboard } from '../..\\components\\page\\userDashboard\\myDashboard.vue'
export { default as PageUserDashboardOrders } from '../..\\components\\page\\userDashboard\\orders.vue'
export { default as PageUserDashboardPayment } from '../..\\components\\page\\userDashboard\\payment.vue'
export { default as PageUserDashboardProfile } from '../..\\components\\page\\userDashboard\\profile.vue'
export { default as PageUserDashboardSavedAddress } from '../..\\components\\page\\userDashboard\\savedAddress.vue'
export { default as PageUserDashboardSecurity } from '../..\\components\\page\\userDashboard\\security.vue'
export { default as PageUserDashboardWishilist } from '../..\\components\\page\\userDashboard\\wishilist.vue'
export { default as BlogRight } from '../..\\components\\blog\\blogDetails\\blogRight.vue'
export { default as BlogSection } from '../..\\components\\blog\\blogDetails\\blogSection.vue'
export { default as BlogBlogDetailsRelatedBlogCarousel } from '../..\\components\\blog\\blogDetails\\relatedBlogCarousel.vue'
export { default as BlogLeft } from '../..\\components\\blog\\blogRightSidebar\\blogLeft.vue'
export { default as HomeElectronicDemoComponentsBannerWithTimer } from '../..\\components\\home\\electronicDemoComponents\\bannerWithTimer.vue'
export { default as HomeElectronicBanner } from '../..\\components\\home\\electronicDemoComponents\\electronicBanner.vue'
export { default as HomeSlide } from '../..\\components\\home\\electronicDemoComponents\\homeSlide.vue'
export { default as HomeSlider } from '../..\\components\\home\\electronicDemoComponents\\homeSlider.vue'
export { default as HomeElectronicDemoComponentsHurryUpBanner } from '../..\\components\\home\\electronicDemoComponents\\hurryUpBanner.vue'
export { default as HomeElectronicDemoComponentsInstagramShop } from '../..\\components\\home\\electronicDemoComponents\\instagramShop.vue'
export { default as HomeElectronicDemoComponentsOurCollectionCarousel } from '../..\\components\\home\\electronicDemoComponents\\ourCollectionCarousel.vue'
export { default as HomeElectronicDemoComponentsTopBar } from '../..\\components\\home\\electronicDemoComponents\\topBar.vue'
export { default as HomeElectronicDemoComponentsVrCollectionCarousel } from '../..\\components\\home\\electronicDemoComponents\\vrCollectionCarousel.vue'
export { default as HomeFashionDemoComponentsCustomerServices } from '../..\\components\\home\\fashionDemoComponents\\customerServices.vue'
export { default as HomeFashionDemoComponentsDealDayBanner } from '../..\\components\\home\\fashionDemoComponents\\dealDayBanner.vue'
export { default as HomeFashionDemoComponentsInstagramShop } from '../..\\components\\home\\fashionDemoComponents\\instagramShop.vue'
export { default as HomeFashionDemoComponentsNewArrivalCarousel } from '../..\\components\\home\\fashionDemoComponents\\newArrivalCarousel.vue'
export { default as HomeFashionDemoComponentsNewArrivals } from '../..\\components\\home\\fashionDemoComponents\\newArrivals.vue'
export { default as HomeFashionDemoComponentsNewOffers } from '../..\\components\\home\\fashionDemoComponents\\newOffers.vue'
export { default as HomeFashionDemoComponentsOurCategory } from '../..\\components\\home\\fashionDemoComponents\\ourCategory.vue'
export { default as HomeFashionDemoComponentsSliderLeftContent } from '../..\\components\\home\\fashionDemoComponents\\sliderLeftContent.vue'
export { default as HomeFashionDemoComponentsSliderShareIcons } from '../..\\components\\home\\fashionDemoComponents\\sliderShareIcons.vue'
export { default as HomeFashionDemoComponentsTopBanner } from '../..\\components\\home\\fashionDemoComponents\\topBanner.vue'
export { default as HomeFlowerDemoComponentsBannerWithTimer } from '../..\\components\\home\\flowerDemoComponents\\bannerWithTimer.vue'
export { default as HomeFlowerDemoComponentsBrand } from '../..\\components\\home\\flowerDemoComponents\\brand.vue'
export { default as HomeFlowerDemoComponentsLatestProducts } from '../..\\components\\home\\flowerDemoComponents\\latestProducts.vue'
export { default as HomeFlowerDemoComponentsNewOffers } from '../..\\components\\home\\flowerDemoComponents\\newOffers.vue'
export { default as HomeFlowerDemoComponentsNewsAndUpdate } from '../..\\components\\home\\flowerDemoComponents\\newsAndUpdate.vue'
export { default as HomeFlowerDemoComponentsOurCategory } from '../..\\components\\home\\flowerDemoComponents\\ourCategory.vue'
export { default as HomeFlowerDemoComponentsOurProducts } from '../..\\components\\home\\flowerDemoComponents\\ourProducts.vue'
export { default as HomeFlowerDemoComponentsProductsBanner } from '../..\\components\\home\\flowerDemoComponents\\productsBanner.vue'
export { default as HomeFlowerDemoComponentsSubscribe } from '../..\\components\\home\\flowerDemoComponents\\subscribe.vue'
export { default as HomeFlowerDemoComponentsTopBanner } from '../..\\components\\home\\flowerDemoComponents\\topBanner.vue'
export { default as HomeFurnitureDemoComponentsBanner } from '../..\\components\\home\\furnitureDemoComponents\\banner.vue'
export { default as HomeFurnitureDemoComponentsCarousels } from '../..\\components\\home\\furnitureDemoComponents\\carousels.vue'
export { default as HomeFurnitureDemoComponentsDealDayBanner } from '../..\\components\\home\\furnitureDemoComponents\\dealDayBanner.vue'
export { default as HomeFurnitureDemoComponentsHurryUp } from '../..\\components\\home\\furnitureDemoComponents\\hurryUp.vue'
export { default as HomeFurnitureDemoComponentsInstagramShop } from '../..\\components\\home\\furnitureDemoComponents\\instagramShop.vue'
export { default as HomeFurnitureDemoComponentsNewArrival } from '../..\\components\\home\\furnitureDemoComponents\\newArrival.vue'
export { default as HomeFurnitureDemoComponentsOurProducts } from '../..\\components\\home\\furnitureDemoComponents\\ourProducts.vue'
export { default as HomeFurnitureDemoComponentsService } from '../..\\components\\home\\furnitureDemoComponents\\service.vue'
export { default as HomeShoesDemoComponentsDealDayBanner } from '../..\\components\\home\\shoesDemoComponents\\dealDayBanner.vue'
export { default as HomeShoesDemoComponentsLatestProductsSlider } from '../..\\components\\home\\shoesDemoComponents\\latestProductsSlider.vue'
export { default as HomeShoesDemoComponentsNewArrivalCarousel } from '../..\\components\\home\\shoesDemoComponents\\newArrivalCarousel.vue'
export { default as HomeShoesDemoComponentsNewOffersBanner } from '../..\\components\\home\\shoesDemoComponents\\newOffersBanner.vue'
export { default as HomeShoesDemoComponentsOurCategory } from '../..\\components\\home\\shoesDemoComponents\\ourCategory.vue'
export { default as HomeShoesDemoComponentsTopBanner } from '../..\\components\\home\\shoesDemoComponents\\topBanner.vue'
export { default as HomeVegetableDemoComponentsBannerWithTimer } from '../..\\components\\home\\vegetableDemoComponents\\bannerWithTimer.vue'
export { default as HomeVegetableDemoComponentsFreshFruitsCarousel } from '../..\\components\\home\\vegetableDemoComponents\\freshFruitsCarousel.vue'
export { default as HomeVegetableDemoComponentsHurryUpBanner } from '../..\\components\\home\\vegetableDemoComponents\\hurryUpBanner.vue'
export { default as HomeVegetableDemoComponentsNewArrivalSection } from '../..\\components\\home\\vegetableDemoComponents\\newArrivalSection.vue'
export { default as HomeVegetableDemoComponentsNewsAndUpdate } from '../..\\components\\home\\vegetableDemoComponents\\newsAndUpdate.vue'
export { default as HomeVegetableDemoComponentsProductsSection } from '../..\\components\\home\\vegetableDemoComponents\\productsSection.vue'
export { default as HomeVegetableDemoComponentsPromoCode } from '../..\\components\\home\\vegetableDemoComponents\\promoCode.vue'
export { default as HomeVegetableBanner } from '../..\\components\\home\\vegetableDemoComponents\\vegetableBanner.vue'
export { default as ProductProduct360ViewShopSection } from '../..\\components\\product\\product360View\\shopSection.vue'
export { default as ProductImages } from '../..\\components\\product\\product4Images\\productImages.vue'
export { default as ProductProduct4ImagesShopSection } from '../..\\components\\product\\product4Images\\shopSection.vue'
export { default as ProductProduct4ImagesTabs } from '../..\\components\\product\\product4Images\\tabs.vue'
export { default as ProductProductBundleFrequentlyBought } from '../..\\components\\product\\productBundle\\frequentlyBought.vue'
export { default as ProductProductBundleShopSection } from '../..\\components\\product\\productBundle\\shopSection.vue'
export { default as ProductProductLeftSidebar } from '../..\\components\\product\\productLeftSidebar\\leftSidebar.vue'
export { default as ProductProductLeftSidebarShopSection } from '../..\\components\\product\\productLeftSidebar\\shopSection.vue'
export { default as ProductProductLeftThumbnailShopSection } from '../..\\components\\product\\productLeftThumbnail\\shopSection.vue'
export { default as ProductProductNoSidebarShopSection } from '../..\\components\\product\\productNoSidebar\\shopSection.vue'
export { default as ProductProductRightSidebar } from '../..\\components\\product\\productRightSidebar\\rightSidebar.vue'
export { default as ProductProductRightSidebarShopSection } from '../..\\components\\product\\productRightSidebar\\shopSection.vue'
export { default as ProductProductRightThumbnailShopSection } from '../..\\components\\product\\productRightThumbnail\\shopSection.vue'
export { default as ProductProductStickyProductsImage } from '../..\\components\\product\\productSticky\\productsImage.vue'
export { default as ProductProductStickyShopSection } from '../..\\components\\product\\productSticky\\shopSection.vue'
export { default as ProductProductVideoThumbnailLeftSidebar } from '../..\\components\\product\\productVideoThumbnail\\leftSidebar.vue'
export { default as ProductSection } from '../..\\components\\product\\productVideoThumbnail\\productSection.vue'
export { default as ProductProductVideoThumbnailShopSection } from '../..\\components\\product\\productVideoThumbnail\\shopSection.vue'
export { default as ProductProductVideoPlayModal } from '../..\\components\\product\\productVideoThumbnail\\videoPlayModal.vue'
export { default as ShopShopCanvasFilterOffCanvasSection } from '../..\\components\\shop\\shopCanvasFilter\\offCanvasSection.vue'
export { default as ShopSection } from '../..\\components\\shop\\shopCanvasFilter\\shopSection.vue'
export { default as ShopShopCategorySlider } from '../..\\components\\shop\\shopCategoryFilter\\categorySlider.vue'
export { default as ShopFilterBar } from '../..\\components\\shop\\shopFilterHide\\shopFilterBar.vue'
export { default as ShopShopTopFilterBar } from '../..\\components\\shop\\shopTopFilter\\topFilterBar.vue'
export { default as ShopShopTopFilters } from '../..\\components\\shop\\shopTopFilter\\topFilters.vue'
export { default as ShopShopWithCategoryTopCategories } from '../..\\components\\shop\\shopWithCategory\\topCategories.vue'
export { default as ShopShopWithCategoryTopCategory } from '../..\\components\\shop\\shopWithCategory\\topCategory.vue'
export { default as VoxoPlusElementPageElementDealBanner1 } from '../..\\components\\voxo_plus\\element_page\\element_deal_banner\\dealBanner1.vue'
export { default as VoxoPlusElementPageElementDealBanner2 } from '../..\\components\\voxo_plus\\element_page\\element_deal_banner\\dealBanner2.vue'
export { default as VoxoPlusElementPageElementDealBanner3 } from '../..\\components\\voxo_plus\\element_page\\element_deal_banner\\dealBanner3.vue'
export { default as VoxoPlusElementPageElementDealBanner4 } from '../..\\components\\voxo_plus\\element_page\\element_deal_banner\\dealBanner4.vue'
export { default as VoxoPlusElementPageElementCategoriesCategorySlider1 } from '../..\\components\\voxo_plus\\element_page\\element_categories\\categorySlider1.vue'
export { default as VoxoPlusElementPageElementCategoriesCategorySlider2 } from '../..\\components\\voxo_plus\\element_page\\element_categories\\categorySlider2.vue'
export { default as VoxoPlusElementPageElementCategoriesCategorySlider3 } from '../..\\components\\voxo_plus\\element_page\\element_categories\\categorySlider3.vue'
export { default as VoxoPlusElementPageElementCollectionBanner1 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner1.vue'
export { default as VoxoPlusElementPageElementCollectionBanner2 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner2.vue'
export { default as VoxoPlusElementPageElementCollectionBanner3 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner3.vue'
export { default as VoxoPlusElementPageElementCollectionBanner4 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner4.vue'
export { default as VoxoPlusElementPageElementCollectionBanner5 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner5.vue'
export { default as VoxoPlusElementPageElementCollectionBanner6 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner6.vue'
export { default as VoxoPlusElementPageElementCollectionBanner7 } from '../..\\components\\voxo_plus\\element_page\\element_collection_banner\\banner7.vue'
export { default as VoxoPlusElementPageElementButtonsBootstrapButtons } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\bootstrapButtons.vue'
export { default as VoxoPlusElementPageElementButtonsButtonBlock } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\buttonBlock.vue'
export { default as VoxoPlusElementPageElementButtonsButtonGroup } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\buttonGroup.vue'
export { default as VoxoPlusElementPageElementButtonsButtonOutline } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\buttonOutline.vue'
export { default as VoxoPlusElementPageElementButtons } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\buttons.vue'
export { default as VoxoPlusElementPageElementButtonsButtonTextSize } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\buttonTextSize.vue'
export { default as VoxoPlusElementPageElementButtonsRoundedButtons } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\roundedButtons.vue'
export { default as VoxoPlusElementPageElementButtonsThemeButtons } from '../..\\components\\voxo_plus\\element_page\\element_buttons\\themeButtons.vue'
export { default as VoxoPlusElementPageElementProductSlider1 } from '../..\\components\\voxo_plus\\element_page\\element_product\\productSlider1.vue'
export { default as VoxoPlusElementPageElementProductSlider2 } from '../..\\components\\voxo_plus\\element_page\\element_product\\productSlider2.vue'
export { default as VoxoPlusElementPageElementProductSlider3 } from '../..\\components\\voxo_plus\\element_page\\element_product\\productSlider3.vue'
export { default as VoxoPlusElementPageElementProductSlider4 } from '../..\\components\\voxo_plus\\element_page\\element_product\\productSlider4.vue'
export { default as VoxoPlusElementPageElementProductSlider5 } from '../..\\components\\voxo_plus\\element_page\\element_product\\productSlider5.vue'
export { default as VoxoPlusElementPageElementProductSlider6 } from '../..\\components\\voxo_plus\\element_page\\element_product\\productSlider6.vue'
export { default as VoxoPlusElementHeader1 } from '../..\\components\\voxo_plus\\element_page\\element_header\\elementHeader1.vue'
export { default as VoxoPlusElementHeader2 } from '../..\\components\\voxo_plus\\element_page\\element_header\\elementHeader2.vue'
export { default as VoxoPlusElementHeader3 } from '../..\\components\\voxo_plus\\element_page\\element_header\\elementHeader3.vue'
export { default as VoxoPlusElementHeader4 } from '../..\\components\\voxo_plus\\element_page\\element_header\\elementHeader4.vue'
export { default as VoxoPlusElementHeader5 } from '../..\\components\\voxo_plus\\element_page\\element_header\\elementHeader5.vue'
export { default as VoxoPlusElementPageElementHomeSlider1 } from '../..\\components\\voxo_plus\\element_page\\element_home\\homeSlider1.vue'
export { default as VoxoPlusElementPageElementHomeSlider2 } from '../..\\components\\voxo_plus\\element_page\\element_home\\homeSlider2.vue'
export { default as VoxoPlusElementPageElementHomeSlider3 } from '../..\\components\\voxo_plus\\element_page\\element_home\\homeSlider3.vue'
export { default as VoxoPlusElementPageElementHomeSlider4 } from '../..\\components\\voxo_plus\\element_page\\element_home\\homeSlider4.vue'
export { default as VoxoPlusElementPageElementHomeSlider5 } from '../..\\components\\voxo_plus\\element_page\\element_home\\homeSlider5.vue'

// nuxt/nuxt.js#8607
function wrapFunctional(options) {
  if (!options || !options.functional) {
    return options
  }

  const propKeys = Array.isArray(options.props) ? options.props : Object.keys(options.props || {})

  return {
    render(h) {
      const attrs = {}
      const props = {}

      for (const key in this.$attrs) {
        if (propKeys.includes(key)) {
          props[key] = this.$attrs[key]
        } else {
          attrs[key] = this.$attrs[key]
        }
      }

      return h(options, {
        on: this.$listeners,
        attrs,
        props,
        scopedSlots: this.$scopedSlots,
      }, this.$slots.default)
    }
  }
}
